#!/bin/sh

cc=clang
cflags=-I.
objdir=obj
sdk=macosx
exec=toolbox
extern_path=extern
progs_file=progs.txt

declarations=
entry_points=
combined_objs=
ldflags=

xcode_path=$(xcode-select -p 2> /dev/null)

if [ ! $? -eq 0 ] || [ -z "$xcode_path" ] || [ "$xcode_path" = /Library/Developer/CommandLineTools ]
then
	printf 'Error: Xcode is not installed.\n' 1>&2
	exit 1
fi

if [ "$1" = clean ]
then
	for d in "$extern_path"/*/*.xcodeproj
	do
		if [ -d "$d" ]
		then
			printf '=== Cleaning %s ===\n' "$d"
			xcodebuild -sdk "$sdk" -project "$d" -UseNewBuildSystem=NO clean
		fi
	done

	rm -f "$objdir"/*.o gen/progs.h gen/*_main.c log/*.txt "$exec"

	exit 0
elif [ "$1" = recovery ]
then
	progs_file=progs-recovery.txt
elif [ ! -z "$1" ]
then
	printf 'Usage ./build [clean | recovery]\n' 1>&2
	exit 1
fi

if [ ! -f "$progs_file" ]
then
	printf 'Error: Input file '\'%s\'' not found.\n' "$progs_file" 1>&2
	exit 1
fi

while IFS=, read -r project aliases flags
do
	prog=$(echo "$aliases" | cut -f1 -d' ')

	echo Building "$aliases"

	project_path=$extern_path/$project

	xcodebuild -sdk "$sdk" -project "$project_path"/"$project".xcodeproj -target "$prog" -UseNewBuildSystem=NO &> log/"$prog".txt

	exit_status=$?

	linkfilelist=$(echo $project_path/build/$project.build/Release/$prog.build/Objects-normal/x86_64/*.LinkFileList)

	if [ ! -e "$linkfilelist" ]; then
		printf 'Error: xcodebuild failed (exit: %d)\n' "$exit_status" 1>&2
		exit 1
	fi

	objs=$(tr '\n' ' ' < $linkfilelist)

	sed s/%NAME%/"$prog"/ main_wrap.c.tpl > gen/"$prog"_main.c
	$cc $cflags -c gen/"$prog"_main.c -o "$objdir"/"$prog"_main.o

	for name in $aliases
	do
		declarations="$declarations extern int ${prog}_main();"
		entry_points="$entry_points {\"$name\", ${prog}_main},"
	done

	$cc $cflags -nostdlib -Wl,-r,-exported_symbol,_"$prog"_main -o "$objdir"/"$prog"_combined.o $objs "$objdir"/"$prog"_main.o

	combined_objs="$combined_objs $objdir/${prog}_combined.o"

	if [ ! -z "$flags" ]
	then
		ldflags="$ldflags $flags"
	fi
done < "$progs_file"

sed -e s/%DECLARATIONS%/"$declarations"/ -e s/%ENTRY_POINTS%/"$entry_points"/ progs.h.tpl > gen/progs.h

echo LDFLAGS: $ldflags

$cc $cflags -c main.c -o "$objdir"/main.o
$cc $cflags $ldflags $combined_objs "$objdir"/main.o -o "$exec"
